import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mori = localFont({
  src: [
    {
      path: "../public/fonts/PPMori-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/PPMori-ThinItalic.woff2",
      weight: "100",
      style: "italic",
    },
    {
      path: "../public/fonts/PPMori-Extralight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/PPMori-ExtralightItalic.woff2",
      weight: "200",
      style: "italic",
    },
    {
      path: "../public/fonts/PPMori-Book.woff2",
      weight: "350",
      style: "normal",
    },
    {
      path: "../public/fonts/PPMori-BookItalic.woff2",
      weight: "350",
      style: "italic",
    },
    {
      path: "../public/fonts/PPMori-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/PPMori-RegularItalic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/PPMori-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/PPMori-SemiboldItalic.woff2",
      weight: "600",
      style: "italic",
    },
    {
      path: "../public/fonts/PPMori-Extrabold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/PPMori-ExtraboldItalic.woff2",
      weight: "800",
      style: "italic",
    },
    {
      path: "../public/fonts/PPMori-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/PPMori-BlackItalic.woff2",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-mori",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mori.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
